# Generated by Django 3.2.1 on 2021-08-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Образовательная программа')),
            ],
            options={
                'verbose_name': 'Образовательную программу',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('otch', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('language', models.CharField(choices=[('Русский', 'Русский'), ('Казахский', 'Казахский')], max_length=255, verbose_name='Язык обучения')),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='id_card/', verbose_name='Лицевая сторона уд.лич')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='id_card/', verbose_name='Обратная сторона уд.лич')),
                ('diplom', models.FileField(upload_to='diplom/', verbose_name='Диплом')),
                ('zayavka', models.FileField(upload_to='zayavka/', verbose_name='Заявка для приема на учебу')),
                ('fluro', models.FileField(upload_to='fluro/', verbose_name='075-y(флюрография)')),
                ('zdorovie', models.FileField(upload_to='zdorovie/', verbose_name='063-y(Паспорт о здоровье)')),
                ('photo', models.FileField(upload_to='photo/', verbose_name='3x4 фото')),
                ('edu_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eduprogram', verbose_name='Образовательная программа')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
